name: Perks
description: Give perks to your players
author: StarTux
version: 0.1
main: com.winthier.perks.bukkit.PerksPlugin
depend: [ Vault, PlayerCache ]
commands:
  perks:
    description: Admin interface to Perks
    permission: perks.perks
    usage: /<command>
permissions:
  perks.perks:
    description: Use the /perks command
    default: op
  perks.admin:
    description: Use the /perks command as an admin
    default: op